### ISSUE TITLE
Feat: Allow to compare with current buffer

### ISSUE THREAD

**Issue by zippeurfou** [David-Kunz/gen.nvim#37] opened 2023-11-22 01:09 UTC
Hey there,
It would be great to be able to compare the new output when we generate code with the previous when when text is selected.
At a high level it could be an interface similar to vim fugitive:
![image](https://github.com/David-Kunz/gen.nvim/assets/4520383/60474269-04e7-48be-a428-c05ec796b380)
It does not need to be as complex but I think this would help where we can decide if we want to accept some / all the chunk and compare with what we had.
Best,

**Comment by David-Kunz** [comment] 2023-11-22 08:11
Hi @zippeurfou ,

Thank you for this suggestion. It's a duplicate of https://github.com/David-Kunz/gen.nvim/issues/18, let's move the discussion there.

**Closed** 2023-11-22 10:13 UTC
