### ISSUE TITLE
Output window remains blank

### ISSUE THREAD

**Issue by siblanco** [David-Kunz/gen.nvim#32] opened 2023-11-18 10:25 UTC
hi there,

thanks for the plugin! 

I am trying it out but - unfortunately - cannot get ollamas output to display inside of nvim.
Running the commands the plugin runs in my terminal directly, everything works fine.

Here's a mp4:
https://storage.siblanco.dev/gen-nvim.mp4

Neovim version:
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

Any idea how I could debug this further?
Please, let me know what else I could provide.

**Comment by dmitriypereverza** [comment] 2023-11-18 12:44
i have the same error

**Comment by nrdlab** [comment] 2023-11-18 21:06
Same here !

**Comment by kapral18** [comment] 2023-11-19 00:44
Same

**Comment by macukadam** [comment] 2023-11-19 00:49
I also had the same issue on my system:

Ubuntu 22.04.3 LTS
Alacritty 0.13.0-dev
NVIM v0.10.0-dev

After debugging for a while. I've fixed it by setting pyt=true. Below is the full code.

```lua
    job_id = vim.fn.jobstart(cmd, {
        on_stdout = function(_, data, _)
            -- window was closed, so cancel the job
            if not vim.api.nvim_win_is_valid(float_win) then
                vim.fn.jobstop(job_id)
                return
            end
            -- Remove carriage returns from each line
            for i, line in ipairs(data) do
                data[i] = line:gsub('\r', '')
            end
            result_string = result_string .. table.concat(data, '\n')
            lines = vim.split(result_string, '\n', true)
            vim.api.nvim_buf_set_lines(result_buffer, 0, -1, false, lines)
            vim.api.nvim_win_call(float_win, function()
                vim.fn.feedkeys('$')
            end)
        end,
        on_stderr = function(_, data, _)
            if opts.debugCommand then
                -- window was closed, so cancel the job
                if not vim.api.nvim_win_is_valid(float_win) then
                    vim.fn.jobstop(job_id)
                    return
                end
                result_string = result_string .. table.concat(data, '\n')
                lines = vim.split(result_string, '\n', true)
                vim.api.nvim_buf_set_lines(result_buffer, 0, -1, false, lines)
                vim.api.nvim_win_call(float_win, function()
                    vim.fn.feedkeys('$')
                end)
            end
        end,
        stderr_buffered = opts.debugCommand,
        pty = true,
        on_exit = function(a, b)
            if b == 0 and opts.replace then
                if extractor then
                    local extracted = result_string:match(extractor)
                    if not extracted then
                        vim.cmd('bd ' .. result_buffer)
                        return
                    end
                    lines = vim.split(extracted, '\n', true)
                end
                lines = trim_table(lines)
                vim.api.nvim_buf_set_text(curr_buffer, start_pos[2] - 1,
                    start_pos[3] - 1, end_pos[2] - 1,
                    end_pos[3] - 1, lines)
                vim.cmd('bd ' .. result_buffer)
            end
        end
    })
    vim.keymap.set('n', '<esc>', function() vim.fn.jobstop(job_id) end,
        { buffer = result_buffer })

    vim.api.nvim_buf_attach(result_buffer, false,
        { on_detach = function() result_buffer = nil end })
end

```

Nvim help for jobstart() states:
pty: (boolean) Connect the job to a new pseudo
 terminal, and its streams to the master file
descriptor. `on_stdout` receives all output,
 `on_stderr` is ignored.
 
Hope it helps.

**Comment by kjjuno** [comment] 2023-11-19 05:06
Does this code work for you? https://github.com/kjjuno/gen.nvim

This is the code for https://github.com/David-Kunz/gen.nvim/pull/31

and I believe it will fix this issue

**Comment by nrdlab** [comment] 2023-11-19 07:55
With this config and Docker running is working on my side 

```lua
return {
  "David-Kunz/gen.nvim",
  config = function()
    vim.keymap.set("v", "<leader>gn", ":Gen<CR>")
    vim.keymap.set("n", "<leader>gn", ":Gen<CR>")
    require("gen").model = "mistral:instruct"
    require("gen").container = "ollama"
  end,
}
```

**Comment by corsettiDev** [comment] 2023-11-19 16:30
> Does this code work for you? https://github.com/kjjuno/gen.nvim
> 
> This is the code for #31
> 
> and I believe it will fix this issue

I'm having the same issue and this fork did not solve the issue for me.

**Comment by kjjuno** [comment] 2023-11-19 18:18
After I posted that I realized I hadn’t addressed your issue. Are you on Linux?

**Comment by Ghasak** [comment] 2023-11-19 18:29
I am using Mac and still having an empty buffer! Any new update on this issue! The plug-in was working flawlessly last week!

**Comment by corsettiDev** [comment] 2023-11-19 19:00
I'm using Mac as well, Sonoma 14.0

**Comment by dmitriypereverza** [comment] 2023-11-19 19:18
Maybe it's related to output buffering

**Comment by siblanco** [comment] 2023-11-19 20:35
> Does this code work for you? https://github.com/kjjuno/gen.nvim
> 
> This is the code for #31
> 
> and I believe it will fix this issue

This works, it opens the output in a new split window and actually outputs stuff...I like it, thank you.

Btw. I am on arch linux using kitty  0.31.0

**Comment by kapral18** [comment] 2023-11-19 21:16
I tried all suggestions above and none fully work. Most don't. Some fix this specific problem but break everything else or mess up the output. I also tried to use earlier commit versions, still unsuccessfully. @David-Kunz do you have this problem?

**Comment by hampgoodwin** [comment] 2023-11-19 22:38
I'm actively trying to debug this, but I am fairly new to nvim, like most of us here 😂 . I've enabled dev for this and am doing iterations testing this out.

So far I suspect something with the buffer, as suggested by @dmitriypereverza . I have attempted both my local dev plugin and the official David-Kunz/gen.nvim plugin and getting nothing in the buffer after running the `Ask` prompt. 

I am testing by:

1. Calling vim user command `:Gen` ( i do this both via keymap and typing :Gen, since I saw in another issue some folks were having trouble which these)
1. Providing a simple prompt like "what is 2+2?"
1. Waiting some time (maybe ~30 seconds)
1. running the vim command `:%p

**Comment by ch-tactica** [comment] 2023-11-19 22:38
@macukadam's fix worked for me, however the ollama startup spinner seems to be adding a bunch of braille glyphs into my buffer, I can possibly live with this... 🤣

**Comment by hampgoodwin** [comment] 2023-11-19 22:46
Ooh, thankyou @macukadam and @ch-tactica ,. This a at least some progress. Like ch-tactica has mentioned, I now get all the braille indicating that the response is processing.

For those who are less experienced like me, I accomplished this by by the plugin in dev mode against a local clone of this repo, then modified the code  in the init.lua file in the repo, as mentioned by @macukadam .

Going to work with this a bit more.

**Comment by ch-tactica** [comment] 2023-11-19 22:50
Makes me think, maybe something changed with the way ollama returns output that is causing things to break, I've had to update a billion things within the past 48 hours and I wouldn't be surprised if some ollama updates snuck in there. They did have a release a few days ago, looks like they did make some changes to ollama run in particular:

https://github.com/jmorganca/ollama/releases/tag/v0.1.10

**Comment by hampgoodwin** [comment] 2023-11-19 22:51
Ooh, great thinking. I will attempt to downgrade my ollama version to maybe a month ago, and rerun it without the pty modification to see if that helps.

**Comment by hampgoodwin** [comment] 2023-11-19 23:03
I just downgraded to ollama@0.1.5 (from about a month ago) and it works exactly as expected; so I think you're correct that this is a difference in how ollama writes to stdout.

**Comment by yesiddev** [comment] 2023-11-19 23:22
You have all the reason the problem is the version of Ollama, then now if we want to use the latest releases then we must await an update in the gen.nvim that solve the recent incompatibility with the output.

**Comment by hampgoodwin** [comment] 2023-11-19 23:31
Yeah. I'll see what I can do. As @ch-tactica has mentioned, v0.1.10 has added wordwrap updates; so I am going to attempt to add a run opt of --nowordwrap to the cmd with v0.1.10 ollama and see if that helps. This will probably be the last thing I can do for today.

**Comment by kjjuno** [comment] 2023-11-19 23:39
I have a PR up that adds conversation support. In order to add that I had to switch to the REST api. I think that might be the better direction anyway.

**Comment by stefanadelbert** [comment] 2023-11-20 06:21
Using the ollama REST API seems like a good way to do this kind of integration. Good call.

**Comment by stefanadelbert** [comment] 2023-11-20 09:08
Although... I've been looking at how to make a POST request from a lua neovim plugin and it's really not obvious! One recommendation is to use `rest-nvim/rest.nvim`, which seems like an overkill.
Generally speaking, you could use `socket.http`, but that's not available from a lua neovim plugin and I think that's because it's not part of the lua standard library.
Any ideas?

**Comment by David-Kunz** [comment] 2023-11-20 09:23
Hi,

With the latest update of `ollama`, I can reproduce this issue. I'll have a look.

**Comment by hampgoodwin** [comment] 2023-11-20 15:47
@David-Kunz I suspect something with how we're detecting `on_stdout` is part of the problem. Just as a test to see if we were getting anything on std out, I was attemting to nvim_buf_set_lines with just a hardcoded table of string, and nothing was ever written to the screen.

I suspect the way that ollama detects where the cmd is being ran from and [how it subsequently creates output](https://github.com/jmorganca/ollama/blob/41434a7cdcf33918ae2d37eb23d819ef7361e843/cmd/cmd.go#L404-L417) may have something to do with it.

OK, I have to go to work for the day :)

**Comment by hampgoodwin** [comment] 2023-11-20 16:47
> Thank you, @hampgoodwin , yes, that's also what I saw. None of the [channel callbacks](https://neovim.io/doc/user/channel.html#channel-callback) are called. I tried the ollama `--nowordwrap` flag (since someone above mentioned that it might have something to do with that change), without success.
> 
> I will check the carriage return proposal, thank you!

I did notice that the [nowordwrap flag is not taken into account if ollama believes the data is coming from a piped command](https://github.com/jmorganca/ollama/blob/6066c70eddd9133160da66942073e122bdd81cd8/cmd/cmd.go#L428C1-L431C3), which is possible since I believe jobstart is not ran 'as a terminal', hence why adding `pty=true,` may have gotten the values actually writing.

These are all wild assumptions on my end, I'm very new to Lua. Thank you for this rad plugin and I'll continue to try to help where I can.

**Comment by hampgoodwin** [comment] 2023-11-20 16:48
OH, I bet that is it.. I bet we need to set pty=true, on_stdout filter the progress symbols, and then write any other symbols... Let me know if you think that is a good path; if someone else is unable to get a start on this before I'm off work I will get started and see how that pans out.

**Comment by David-Kunz** [comment] 2023-11-20 16:52
That did the trick, @hampgoodwin .

```diff
    job_id = vim.fn.jobstart(cmd, {
+        pty = true,
```

Now, I get the result, but also weird symbols.

**Comment by David-Kunz** [comment] 2023-11-20 17:07
I'm thinking of making all of this simpler and just spawn a


```
:te ollama run ...
```

That also works.

**Comment by hampgoodwin** [comment] 2023-11-20 17:32
Awesome!
Let me know if you make a PR and want second eyes on it or want me to test the changes.

**Comment by David-Kunz** [comment] 2023-11-20 17:43
Thank you, @hampgoodwin !

The following works:

```lua
    vim.api.nvim_buf_call(result_buffer, function()
      vim.fn.termopen(cmd, {
        on_exit = function(a, b)
          if b == 0 and opts.replace then
              local lines = trim_table(vim.api.nvim_buf_get_lines(result_buffer, 0, -1, false))
              local text = table.concat(lines, '\n')
              if extractor then
                  local extracted = text:match(extractor)
                  if not extracted then
                      vim.cmd('bd ' .. result_buffer)
                      return
                  end
                  lines = vim.split(extracted, '\n', true)
              end
              vim.api.nvim_buf_set_text(curr_buffer, start_pos[2] - 1,
                                        start_pos[3] - 1, end_pos[2] - 1,
                                        end_pos[3] - 1, lines)
              vim.cmd('bd ' .. result_buffer)
          end
        end
      })
    end)
```

but now the result is not displayed in markdown highlighting :(

**Comment by David-Kunz** [comment] 2023-11-20 17:46
I merged it into main: https://github.com/David-Kunz/gen.nvim/commit/501fe1f7ef801efa26e9c446ba58ab51e8cfedf7

It would be great, if you could test it, @hampgoodwin ! Now, I need to figure out how to solve the markdown highlighting with `termopen`.

**Comment by David-Kunz** [comment] 2023-11-20 18:09
So `set syntax=on` give me at lest some syntax highlighting, not based on Tree-Sitter though. `set filetype=markdown` doesn't do it as previously.

**Comment by hampgoodwin** [comment] 2023-11-20 18:15
I will check it out; I have treesitter and markdown installed for it. Would this be when you attempt to replace some buffer text with a prompt suggestion? (I have not used that feature yet, only Ask)

**Comment by David-Kunz** [comment] 2023-11-20 18:18
Thank you, @hampgoodwin !

Whenever the window opens to show the generated text, it should be properly highlighted with Tree-Sitter, but that's currently not the case. The best I could do for now is `set syntax=on`, but that doesn't use Tree-Sitter. I'll need to do more investigations.

**Comment by hampgoodwin** [comment] 2023-11-20 18:32
I see; I had not noticed syntax highlighting before, but I haven't been using the plugin. I experience the same.

Should we close this issue since we're able to get output on the screen and start another issue for this?

Also, if you have time sometime this week I'd enjoy discussing where you see the project going and where I could contribute to your vision of it.

<img width="1438" alt="image" src="https://github.com/David-Kunz/gen.nvim/assets/17371239/ca2cd5ca-ce9a-4deb-a9a0-0968d447f871">

**Comment by hampgoodwin** [comment] 2023-11-20 18:46
I bet we're losing the treesitter highlighting because we're launching it as a pseudoterminal, instead of as a codeeditor window? That could cause nvim to _not_ load some things?

**Comment by David-Kunz** [comment] 2023-11-21 13:37
Thanks a lot, @hampgoodwin ! It would be fantastic to talk with you and share ideas!

**Closed** 2023-11-21 14:24 UTC
